site_name: Wizeline DocOps Template
nav:
  - Home: index.md
  - About: about.md
  - JC-Test: jc-test.md
  
theme:
  name: material
  palette:
    primary: black
    accent: indigo
  logo: images/wizeline_isotype.png
